### PR TITLE
remove night and home mode and only display away

### PR DESCRIPTION
**Pull request by donavanbecker**

### CODE REVIEW

**Comment by thomaspirard** [comment]
+1

**Comment by colinbendell** [comment]
I've waffled on this back and forth. Originally I had it as you described, but then had a request from someone who use the state (eg: 'night') to specify different camera configurations (eg: arm the downstairs cameras only in night mode arming). In reality, I think I'm leaning toward removing the security system all together and exposing a motion switch for each camera. This would imply if at least one motion switch is enabled then the blink system would arm. In this way, the cameras can be automated in different ways without also having to think about the macro context of a global arm/disarm. Open to thoughts though.

**Comment by donavanbecker** [comment]
@colinbendell yeah either way. you could also make the alarm system a config where you can enable or disable night mode and home mode? and then if home mode is enabled it is used for something and save with night mode. I think have the security system makes if feel more native HomeKit support but that's just me.

**Comment by hunterpaul** [comment]
I agree with you re the security system element. I use the plugin to automate my cameras so that they arm/disarm at specific times or based on our location I.e when we leave or arrive home. I don’t use the security system element at all as you have to confirm that you want it to run it (HomeKit requirement) which is a bind or easily overlooked leaving the system disarmed. I just use the ‘Blink Armed’ function to arm/disarm the system then  activate/deactivate each camera as required. If you could arm or disarm the system based on camera status, that would make automations so much easier and there would be no need to have specific cameras active based on security system status, your automations would just specify which cameras you want active and when.

**Comment by WhooKnew** [comment]
I made Dummy Switch in Homebridge.
When i leave Home -> Dummy Switch Turn on.
When Dummy Switch is On -> Arm Camera System

So you do not have manual to allow the activation of the Automatication.

Maye its useful for you, otherwise please ignore :-)

**Comment by colinbendell** [comment]
That's what the Manual Arm switch does in the current version.

**Comment by rcoletti116** [comment]
> think have the security system makes if feel more native HomeKit support but that's just me.

Not just you. I use it and like it.

**Comment by AlexandreBERGIA** [comment]
> I've waffled on this back and forth. Originally I had it as you described, but then had a request from someone who use the state (eg: 'night') to specify different camera configurations (eg: arm the downstairs cameras only in night mode arming). In reality, I think I'm leaning toward removing the security system all together and exposing a motion switch for each camera. This would imply if at least one motion switch is enabled then the blink system would arm. In this way, the cameras can be automated in different ways without also having to think about the macro context of a global arm/disarm. Open to thoughts though.

We should maintain the Home/Away/Night/Off modes. If people want to use only as on/off that option fulfill the purpose. I'm writing here as there is issue #69 that makes the Home state falling back to Away automatically. I'm forking the project to offer an update soon.
First time I do this kind of project so no promises to have it quickly.

**Comment by colinbendell** [comment]
I've planned to add a bunch of PRs this weekend. if you are able to submit
something by then I can move to include it.

**Pull request closed without merging**
