### PR TITLE
Add More Options To Hide Alarm, Manual Arm Switch, and Enabled Switch

### PR DESCRIPTION
**Pull request by donavanbecker**
add options for Hiding Alarm, Manual arm switch and enabled switch.

* `"hide-alarm": true,`
* `"hide-manual-arm-switch": true,`
* `"hide-enabled-switch": true,`

### CODE REVIEW

**Comment by donavanbecker** [comment]
@colinbendell you may have to make some more changes, but it would be awesome if we could get this PR merged.

**Comment by donavanbecker** [comment]
@colinbendell any thoughts?

**Comment by colinbendell** [comment]
Heya @donavanbecker - I've been cherry picking your PR since it includes a bunch of different changes and the code format change causes merge issues. I'm going to reopen the PR more for a sanity check as I prep for release.

**Comment by donavanbecker** [comment]
@colinbendell Sounds good

**Pull request closed without merging**
